// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	_ "gorm.io/driver/mysql"
	"gorm.io/gorm"
	"time"
)

// 用户信誉资质文件表
type Credit struct {
	Id         uint   `gorm:"column:id;primary_key;AUTO_INCREMENT"`
	UserId     uint   `gorm:"column:user_id;default:0;NOT NULL"`     // 用户ID
	Name       string `gorm:"column:name;NOT NULL"`                  // 名字
	Photos     string `gorm:"column:photos"`                         // 图片
	Phone      string `gorm:"column:phone;NOT NULL"`                 // 手机号
	Amount     string `gorm:"column:amount;default:0.00;NOT NULL"`   // 余额
	Status     uint   `gorm:"column:status;default:0;NOT NULL"`      // 审核状态 (0:未审核, 1:已通过, 2:未通过)
	IsDel      uint   `gorm:"column:is_del;default:0;NOT NULL"`      // 是否删除 (1:是, 0:否)
	CreateTime uint   `gorm:"column:create_time;default:0;NOT NULL"` // 创建时间
	UpdateTime uint   `gorm:"column:update_time;default:0;NOT NULL"` // 更新时间
}

func (m *Credit) TableName() string {
	return "credit"
}

func (u *Credit) BeforeCreate(tx *gorm.DB) (err error) {
	u.CreateTime = uint(time.Now().Unix())
	return
}
